
[UNDER CONSTRUCTION]

(apitest) ~:djangoTestAPI admin$ python manage.py shell
Python 2.7.10 (default, Feb  7 2017, 00:08:15)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from snippets.models import Snippet
>>> from snippets.serializer import SnippetSerializer
>>> from rest_framework.renderers import JSONRenderer
>>> from rest_framework.parsers import JSONParser

>>> snippet = Snippet(code='foo="bar"\n')
>>> snippet.save()
>>> print snippet
Snippet object

>>> snippet = Snippet(code='print "hello, world"\n')
>>> snippet.save()

>>> ser = SnippetSerializer(snippet)
>>> ser.data
{'style': 'friendly', 'code': u'print "hello, world"\n', 'language': 'python', 'title': u'', 'linenos': False, 'id': 2}

>>> content = JSONRenderer().render(ser.data)
>>> content
'{"id":2,"title":"","code":"print \\"hello, world\\"\\n","linenos":false,"language":"python","style":"friendly"}'

>>> from django.utils.six import BytesIO
>>> stream = BytesIO(content)
>>> data = JSONParser().parse(stream)
>>> serializer = SnippetSerializer(data=data)
>>> serializer.is_valid()
True
>>> serializer.validated_data
OrderedDict([(u'title', u''), (u'code', u'print "hello, world"'), (u'linenos', False), (u'language', 'python'), (u'style', 'friendly')])
>>> serializer.save()
<Snippet: Snippet object>

>>> serializer = SnippetSerializer(Snippet.objects.all(), many=True)
>>> serializer.data
[OrderedDict([('id', 1), ('title', u''), ('code', u'foo="bar"\n'), ('linenos', False), ('language', 'python'), ('style', 'friendly')]), OrderedDict([('id', 2), ('title', u''), ('code', u'print "hello, world"\n'), ('linenos', False), ('language', 'python'), ('style', 'friendly')]), OrderedDict([('id', 3), ('title', u''), ('code', u'print "hello, world"'), ('linenos', False), ('language', 'python'), ('style', 'friendly')])]

>>>



[0]:

(apitest) ~:djangoTestAPI admin$ python manage.py runserver
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x101de9d70>
Traceback (most recent call last):
(...)
  File "/Users/zwilhelm/Documents/gitcode/DjangoTestAPI/DjangoTestAPI/djangoTestAPI/snippets/views.py", line 14
    from __future__ import unicode_literals
SyntaxError: from __future__ imports must occur at the beginning of the file

FIX: Put the 'from __future__ import'; 



[1]:

Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x1014b8d70>
Traceback (most recent call last):
(...)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named urls

FIX: Commented out snippets.urls from urls patters;






















